### ISSUE TITLE
Webhook and Notification Problem

### ISSUE THREAD

**Issue by xElkomy** [rs-loves-bugs/xsshunter#11]
### Community Note
Hello, When I add my webhook and try to fire any xss to test the  function it doesn't work

### Expected Behavior
When I open the docker in front of me when the firing happend I got this error:

```
xsshunterexpress-service     | Error: Expected `asm` to include an integer in its `groupId` field
xsshunterexpress-service     |     at Mail.setAsm (/app/node_modules/@sendgrid/helpers/classes/mail.js:189:15)
xsshunterexpress-service     |     at Mail.fromData (/app/node_modules/@sendgrid/helpers/classes/mail.js:89:10)
xsshunterexpress-service     |     at new Mail (/app/node_modules/@sendgrid/helpers/classes/mail.js:46:12)
xsshunterexpress-service     |     at Function.create (/app/node_modules/@sendgrid/helpers/classes/mail.js:594:12)
xsshunterexpress-service     |     at MailService.send (/app/node_modules/@sendgrid/mail/src/classes/mail-service.js:194:25)
xsshunterexpress-service     |     at Object.send_email_notification (/app/notification.js:34:3)
xsshunterexpress-service     |     at /app/app.js:410:23
xsshunterexpress-service     |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
xsshunterexpress-service     | TypeError: Cannot read properties of undefined (reading '0')
xsshunterexpress-service     |     at Object.send_email_notification (/app/notification.js:39:58)
xsshunterexpress-service     |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
xsshunterexpress-service     |     at async /app/app.js:410:4
```

![image](https://github.com/rs-loves-bugs/xsshunter/assets/46958133/0d4fa226-38d4-4926-8e88-9154519da9ec)

I hope there are any solutions for this

**Comment by xElkomy** [comment]
Stop the sendgrid from the `.env` and put a one webhook slack or discord or telegram don't put the three togther
